# global constants
USE_TEMPLATE: True # whether to use the preset template
# external call to the program that evaluates the map and returns the result as a JSON
EXT_GMA_CMD: fitness_executable/MinidungeonsConsole.exe
OUTPUT_FOLDER: MD2_mapelites-archive # output folder for the exported levels created
TEMP_CHROME_FOLDER: temp

# experiment parameters
ITERATIONS: 100
MAP_MUTATION_RATE: 0.2
FEASIBLE_SEL_RATE: 0.6
POPSIZE: 5
MAX_SET_SIZE: 5
EMPTY_RATE: 0.5
WALL_RATE: 0.4
CORES: 5
FITNESS_FUNCTION: simplicity
OUTPUT_INTERVAL: 10
INIT_ASCII_TILES:
  [
    "empty",
    "wall",
    "blob",
    "minotaur",
    "trap",
    "treasure",
    "potion",
    "portal",
    "ogre",
    "ogre2",
    "witch",
  ]
MUT_ASCII_TILES: ["empty", "wall", "blob", "trap", "treasure", "potion", "ogre"]

PERSONA: R # runner [R], monster_killer [MK], treasure_collector [TC]
AGENT: AStar
C: 1.0
PLAYCOUNT: 1
ROLLOUT: 1
PARALLEL: True
OUTPUT_ARC: True
GMA_THRESHOLD: 0.8

#MAP ELITES PARAMETERS
MAP_ELITES_DIM: 0.25
ELITE_PROB: 0.8
MAX_CELL_SIZE: 5
DIMENSION_TYPE: health